const HEADER_HEIGHT = 55;
const RADIO_TITLE_HEIGHT = 16;
const BEST_BUTTON_HEIGHT = 80;
const BEST_BUTTON_HEIGHT_MOBILE = 60;

export {
  HEADER_HEIGHT,
  RADIO_TITLE_HEIGHT,
  BEST_BUTTON_HEIGHT,
  BEST_BUTTON_HEIGHT_MOBILE,
};
