import { Countries, Genres, RadioStations } from './types';

const radioStations: RadioStations = [
  {
    id: 1,
    name: 'living sound instrumental',
    genre: 'Adult Pop',
    country: 'United States',
    img: '/img/living-sound-instrumental.png',
  },
  {
    id: 2,
    name: 'anarchy pistols',
    genre: 'Pop',
    country: 'Latvija',
    img: '/img/anarchy-pistols.png',
  },
  {
    id: 3,
    name: 'dance fm',
    genre: 'Dance',
    country: 'Germany',
    img: '/img/dance-fm.png',
  },
  {
    id: 4,
    name: 'europa plus',
    genre: 'Hip-Hop',
    country: 'Russia',
    img: '/img/europa-plus.png',
  },
  {
    id: 5,
    name: 'hip hop music',
    genre: 'Hip-Hop',
    country: 'Russia',
    img: '/img/hip-hop-music.png',
  },
  {
    id: 6,
    name: 'indigo',
    genre: 'Electro',
    country: 'United States',
    img: '/img/indigo.png',
  },
  {
    id: 7,
    name: 'japan-fm',
    genre: 'Rock',
    country: 'Testing',
    img: '/img/japan-fm.png',
  },
  {
    id: 8,
    name: 'love radio',
    genre: 'Pop',
    country: 'Russia',
    img: '/img/love-radio.png',
  },
  {
    id: 9,
    name: 'maximum fm',
    genre: 'Electro',
    country: 'Russia',
    img: '/img/maximum-fm.png',
  },
  {
    id: 10,
    name: 'mcm',
    genre: 'Hip-Hop',
    country: 'Local Radio',
    img: '/img/mcm-fm.png',
  },
  {
    id: 11,
    name: 'пилот фм',
    genre: 'Chanson',
    country: 'Russia',
    img: '/img/pilot-fm.png',
  },
  {
    id: 12,
    name: 'pixel-radio',
    genre: 'Dance',
    country: 'Russia',
    img: '/img/pixel-radio.png',
  },
  {
    id: 13,
    name: 'радио 7',
    genre: 'Power Pop',
    country: 'Russia',
    img: '/img/radio-7.png',
  },
  {
    id: 14,
    name: 'radio tagline',
    genre: 'Rock',
    country: 'Belorussia',
    img: '/img/radio-tagline.png',
  },
  {
    id: 15,
    name: 'record',
    genre: 'Dance',
    country: 'Russia',
    img: '/img/record.png',
  },
  {
    id: 16,
    name: 'ritmo 80',
    genre: 'Adult Pop',
    country: 'Latvija',
    img: '/img/ritmo-80.png',
  },
  {
    id: 17,
    name: 'дорожное радио',
    genre: 'Chanson',
    country: 'Russia',
    img: '/img/road-fm.png',
  },
  {
    id: 18,
    name: 'time',
    genre: 'Rock',
    country: 'Germany',
    img: '/img/time.png',
  },
  {
    id: 19,
    name: 'velena',
    genre: 'r&b soul',
    country: 'Germany',
    img: '/img/velena.png',
  },
  {
    id: 20,
    name: 'разбуди меня',
    genre: 'Hip-Hop',
    country: 'Russia',
    img: '/img/wake-me-up.png',
  },
  {
    id: 21,
    name: 'yo fm',
    genre: 'r&b soul',
    country: 'United States',
    img: '/img/yo-fm.png',
  },
];

const countries: Countries = [
  { id: 1, name: 'Testing' },
  { id: 2, name: 'Local Radio' },
  { id: 3, name: 'Russia', img: '/flags/ru.png' },
  { id: 4, name: 'United States', img: '/flags/us.png' },
  { id: 5, name: 'Germany', img: '/flags/de.png' },
  { id: 6, name: 'Latvija', img: '/flags/lv.png' },
  { id: 7, name: 'Belorussia', img: '/flags/by.png' },
];

const genres: Genres = [
  { id: 1, name: 'Pop' },
  { id: 2, name: 'Adult Pop' },
  { id: 3, name: 'Power Pop' },
  { id: 4, name: 'Dance' },
  { id: 5, name: 'Electro' },
  { id: 6, name: 'Hip-Hop' },
  { id: 7, name: 'r&b soul' },
  { id: 8, name: 'Rock' },
  { id: 9, name: 'Chanson' },
];

export { radioStations, countries, genres };
